version: "2"
services:
  master:
    build: 
            context: tmp/eea.docker.jenkins.master/ 
            dockerfile: Dockerfile 
    ports:
    - "8080:8080"
    - "50000:50000"
    volumes:
    - jenkins-master:/var/jenkins_home

  worker:
    image: eeacms/jenkins-slave
    environment:
      JAVA_OPTS: "-Xmx2048m"
      JENKINS_MASTER: "http://127.0.0.1:8080"
      JENKINS_NAME: "worker"
      JENKINS_USER: "admin"
      JENKINS_PASS: "admin"
      JENKINS_RETRY: "10"
    volumes:
    - jenkins-worker:/var/jenkins_home/worker

volumes:
  jenkins-master:
  jenkins-worker:
