version: "2"
services:
  master:
    image: jenkins/jenkins:lts
    ports:
    - "80:8080"
    - "5000:5000"
    environment:
    - JAVA_OPTS=-Xmx2048m
    volumes:
    - jenkins-master:/var/jenkins_home

  worker:
    image: jenkins/jnlp-slave
    environment:
      JENKINS_MASTER: "http://master:8080"
      JENKINS_AGENT_NAME: "worker"
    volumes:
    - jenkins-worker:/var/jenkins_home/worker

volumes:
  jenkins-master:
  jenkins-worker:
